### ISSUE TITLE
Date Palms missing trunk nodes

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/moretrees#1]
Date Palms missing trunk nodes
Just verified on my game. Trunks are missing from y position 14 through 17. This makes it difficult to have a clean cut using the woodcutter mod. Not sure if the technic chainsaw will cut the whole tree.

Since I haven't found one in the wild, I don't know if the natural spawns are missing the same trunk nodes.

**Comment by SwissalpS** [comment]
I just planted 20 nicely apart on pandorabox. They all grew nicely and the chainsaw cut two nicely with some charge left.

**Comment by wsor4035** [comment]
closing as issue seems to be non existent comment here/open a new issue if otherwise with a reproducible example

**Comment by OgelGames** [comment]
Technic chainsaw has worked cut them fully since https://github.com/mt-mods/technic/commit/30775ff03ffd00367a843ee3eb90dbf903e4fa82, haven't tested woodcutting mod, but it should be fixed in that mod if it doesn't work, not here.

**Comment by daytonnvpaul** [comment]
Sorry for any confusion, but my issue was using the woodcutter mod, not the technic chainsaw.

However, if you look at the actual date palm, after spawning from sapling, it is definitely missing 4 trunk nodes starting at position y = 14.  The missing trunk nodes have occurred every time I have grown a tree from sapling.
