### ISSUE TITLE
big tree

### ISSUE THREAD

**Issue by Pantyhose-X** [mt-mods/moretrees#10]
Request Add a large tree, 10 nodes wide,130 nodes high. This is 130 nodes high with access to white clouds.
Do not use mapgen generation as this would create a flashback bug and only allow manual planting of a big tree

**Comment by Niklp09** [comment]
Doesn't sound really realistic

**Comment by wsor4035** [comment]
seems out of scope of this mod. this has been done in other mods, see https://forum.minetest.net/viewtopic.php?t=16503 and pryllos? big grund? tree mod

**Comment by Pantyhose-X** [comment]
> https://forum.minetest.net/viewtopic.php?t=16503
There are serious big bug Author, no longer maintained
