### ISSUE TITLE
"moretrees_acacia_wood.png" is missing

### ISSUE THREAD

**Issue by vonglahn** [mt-mods/moretrees#16]
Hi,

I get a missing png error message at the start of minetest 5.6.1

ERROR[Main]: generateImage(): Could not load image "moretrees_acacia_wood.png" while building textures; Generate a dummy image

**Comment by Niklp09** [comment]
Are you using other mods with moretrees support?

**Comment by OgelGames** [comment]
That texture was removed over 7 years ago in commit ad0cbbc0fa3061b122ea6f78cdfd00ada110961c. You must be using an old mod that is referencing that texture.

**Comment by vonglahn** [comment]
I'm using a lot of mods but how do I know which other mod uses that texture?

**Comment by Niklp09** [comment]
`egrep -rni -e "moretrees_acacia_wood.png" ./minetest/mods`

replace `./minetest/mods` with your mods path

**Comment by S-S-X** [comment]
> I'm using a lot of mods but how do I know which other mod uses that texture?

Try doing text search in all lua files in mods directory.
For Windows not sure how well builtin search works but notepad++ at least has good search tool that can search directories recursively. 
For Linux `grep -rm1 'moretrees_acacia_wood.png' mods` where mods is minetest mods directory.

**Comment by Niklp09** [comment]
this is not a moretrees issue

**Comment by vonglahn** [comment]
It's an error from columnia.
