### ISSUE TITLE
ongen saplings should probably not be visible in inventory

### ISSUE THREAD

**Issue by fluxionary** [mt-mods/moretrees#18]
they aren't a node a player can normally get, and their use is obscure

**Comment by wsor4035** [comment]
both of the above statements are false, players can get them in creative, and there used also in creative for getting a tree fast.

**Comment by fluxionary** [comment]
actual creative players would of course still be able to get them via "/give" or similar. "not_in_creative_inventory" is poorly named, the actual function is more like "not listed in inventory managers".

**Comment by S-S-X** [comment]
Players do collect those in survival too, yeah apparently not really planned feature but has became part of the game in some servers.
Not 100% sure but I think there was some mods also adding recipes for ongen saplings which does make a lot of sense in some game settings and with reusability without overrides.

If this means making items invisible in normal player inventory then I think it is probably bad idea for legitimate use cases.

**Comment by wsor4035** [comment]
> actual creative players would of course still be able to get them via "/give" or similar. "not_in_creative_inventory" is poorly named, the actual function is more like "not listed in inventory managers".

again, more false information. i dont know which creative servers you visit, but i can assure you that most servers do not grant normal players the ability to use /give. you literally can read the description of the saplings to know there purpose as i stated above: <https://github.com/mt-mods/moretrees/blob/e476b81cf5270adf34b3a19573abf52fbfdfee9d/node_defs.lua#L467> `(fast growth)`

**Comment by S-S-X** [comment]
While my current opinion is that this suggestion is probably bad idea there's apparently other people who do think that there's a good reason to implement this suggestion.

Apparently there's some problem that needs solution, so far there's been some talk and opinions about solution but what is the actual problem that needs to be solved?

**Comment by fluxionary** [comment]
@wsor4035 if you unilaterally close this again without at least waiting for a reply i will absolutely refuse to work w/ you on anything ever again. it's incredibly rude. 

> players do collect those in survival too

i feel like i've seen players end up w/ them somehow, but that's not intended: https://github.com/mt-mods/moretrees/blob/e476b81cf5270adf34b3a19573abf52fbfdfee9d/node_defs.lua#L481

> I think there was some mods also adding recipes for ongen saplings

i know the [flowerpot mod](https://github.com/minetest-mods/flowerpot/blob/1431a640b242605d0a2747fb89481ee34c30ab51/init.lua#L234-L247) does, but they don't do anything, they're basically wastes of node IDs

> i dont know which creative servers you visit

none, but i suppose that's the core of the disagreement here. as you point out, on a creative servers, the ongen variant is probably more useful than the other. i was not thinking about that use when i created this issue. 

the i've got is that on survival servers, the ongen saplings are an "ignore the man behind the curtain" type item. they have no source nor use for players, and the explanation of what they are just goes over their heads. 

> you literally can read the description of the saplings to know there purpose as i stated above

you can look at the verdammte itemstring and see it ends with "_ongen" for "on generation". the code makes their use clear - they're intended as an artifact of map generation. 

i think there's probably still a solution that will make everyone happy. 

do creative mode servers generally actually set `creative_mode = true`, or is it that `creative` is a default priv? if it's that simple, the ongen saplings could be hidden automatically. if it's more ad-hoc, a setting could be created at least, and we can argue about what the default value should be.

**Comment by wsor4035** [comment]
@fluxionary the issue was closed again due to you posting false information both times, as you admit

> none, but i suppose that's the core of the disagreement here. as you point out, on a creative servers, the ongen variant is probably more useful than the other. i was not thinking about that use when i created this issue.

 and the fact that sx agreed 
 
 > If this means making items invisible in normal player inventory then I think it is probably bad idea for legitimate use cases.

just because something is has one use, does not mean it can not have more than that. typically descriptions are what are shown to players, and that is what they see for these saplings

> you can look at the verdammte itemstring and see it ends with "_ongen" for "on generation". the code makes their use clear - they're intended as an artifact of map generation.

im aware that you can do a check for creative mode, and add/remove the group for fast growth/ on gen saplings, however i know that at least a handful of survival server admins with creative, or builders they have working on spawn, etc use these saplings, and to my knowledge, with existing inventory mods, there isnt a way to show an item only if they have the creative priv

**Comment by OgelGames** [comment]
> with existing inventory mods, there isnt a way to show an item only if they have the creative priv

This is the real problem here, what we really need is `not_in_survival_inventory`, and I can think of multiple other places where such a group would be useful.

Shouldn't be too hard to PR this to the various inventory managers...

**Comment by wsor4035** [comment]
> > with existing inventory mods, there isnt a way to show an item only if they have the creative priv
> 
> This is the real problem here, what we really need is `not_in_survival_inventory`, and I can think of multiple other places where such a group would be useful.
> 
> Shouldn't be too hard to PR this to the various inventory managers...

sure, real problem is mtg however, being in feature freeze, and also older version support (its builtin sfinv). could always say older versions just wont be as well supported

**Comment by OgelGames** [comment]
> real problem is mtg however, being in feature freeze

It seems like MTG isn't completely frozen, just a few days ago the `screwdriver` mod got support for the new 4dir rotation type: https://github.com/minetest/minetest_game/commit/99a719309559b632af65756f380496aa269d4b4a

But I think most of the time another inventory mod is used like `unified_inventory` or `i3`, so we probably don't even need to bother with MTG.

**Comment by wsor4035** [comment]
random thought, if effort is going to be taken to pr something to inventory mangers, i could see something like priv based being useful, i.e. showing admin items to people with server, etc. it would be more flexible

**Comment by wsor4035** [comment]
closing with https://github.com/mt-mods/moretrees/commit/7879bd819230f53c615dad97ad4e9a35a55ab0b3 merged, and per discussion, and opening an issue for specifically targeting `not_in_survival_inventory` or priv based group solution
