### ISSUE TITLE
AsyncErr: Runtime error from mod 'moretrees' in callback LuaABM::trigger(): attempt to index a nil value

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/moretrees#2]
AsyncErr: Runtime error from mod 'moretrees' in callback LuaABM::trigger(): attempt to index a nil value
Hello,

I was just testing out the saplings that your mod provides, when it crashed with the following error:
```
AsyncErr: ServerThread::run Lua: Runtime error from mod 'moretrees' in callback LuaABM::trigger(): attempt to index a nil value
stack traceback:
	[C]: in function 'swap_node'
	...minetest/worlds/Mod-Sandbox/worldmods/moretrees/init.lua:202: in function 'grow_birch'
	(load):1: in main chunk
	...minetest/worlds/Mod-Sandbox/worldmods/biome_lib/init.lua:645: in function 'replace_object'
	...minetest/worlds/Mod-Sandbox/worldmods/biome_lib/init.lua:619: in function <...minetest/worlds/Mod-Sandbox/worldmods/biome_lib/init.lua:593>
```
I was placing them on stone in order to see what they looked like and get their node names (using my hud helper mod) because I'm implementing a //forest command, but it crashed :-(

If it helps, I had some mese lamps nearby to illuminate the area, and it was in an enclosed stone box underground.

**Comment by Niklp09** [comment]
The function should not crash when `pos` is given. (and we don't use biome_lib anymore here). closing
