### ISSUE TITLE
dep on ethereal can cause circular dependences - blame is on ethereal/tenplus1 

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/moretrees#22]
ethereal yet again is still nuking things so a dep on it is needed to prevent this.
known circular dep tree: `ethereal --> bakedclay --> flowerpot --> moretrees --> ethereal.`
other issue trackers mentioning this: https://gitea.your-land.de/your-land/bugtracker/issues/3013 (thanks Niklp)

status: need to talk to tenplus1

**Comment by fluxionary** [comment]
> ethereal yet again is still nuking things so a dep on it is needed to prevent this.

isn't the "nuking" (clearing biomes/decorations and re-registering them) now a configurable behavior?

**Comment by wsor4035** [comment]
iirc its now a setting, but it should still properly clear and reregister decorations

**Comment by Awkanimus** [comment]
The "nuking" is in "biome_init.lua" in ethereal's biome_ini.lua which is only triggered when `ethereal.clear_default_biomes` is set true (which it is by default). I happened to be looking at it last night.

The logic seems to be 
1. create a map (table?) of existing biomes
2. create a map (another table?) of existing decorations
3. clear both
4. reregister biomes not on a discard-list, 
5. reregister decorations if they are not in any of the discard-list's biomes.

I'm quite new here and to this codebase; there are of-course probably reasons why ... however I don't quite get why `minetest.unregister_biome` isn't used selectively on items in the discard list nor why decoration removal isn't the same. Also feels like the current method deprives all biomes of certain decos if they appear in even one discard-list biome.

**Comment by Awkanimus** [comment]
I'd be happy to try to solve this in ethereal and submit a pull request there. Does anyone know off-hand one-or-more decos which are disappearing or should I just dump them and look for a `moretrees:` prefix?

**Comment by wsor4035** [comment]
the simple way to test is clone both mods, remove the ethereal dep from moretrees, and add a moretrees dep to ethereal, and then see whats missing

**Comment by wsor4035** [comment]
ideally ethereal should keep its hands off anything that isnt made by it, and/or its directly modifying (like default)

**Comment by Awkanimus** [comment]
Based on my tests, I cannot find any indication that Ethereal is removing moretrees decos. If I missed a case or you'd like something else validated, please let me know.

Test setup: 
1. Brand new world created with MTG (by chance... on a fresh computer with an empty mods folder)
2. Ethereal mod cloned fresh from TenPlus1's ethereal repo
3. Moretrees mod cloned fresh from here
4. Wrote a mod of my own created which uses `minetest.register_on_mods_loaded` to dump deco info after all mods are loaded, ethereal, and moretrees

Sampling procedure:
1. Delete debug.txt
2. Start minetest
3. Toggle the mods on/off to cover the cases
4. Saved debug.txt with names related to the case
5. Extract deco info from logs and compare the results

Cases sampled:
1. Only my own mod loaded
2. Only moretrees loaded
3. Moretrees and ethereal loaded with no modifications
4. Moretrees and ethereal loaded with dependencies reversed (where ethereal deps on moretrees)

Moretrees adds a "decoration" field with a "moretrees:" prefix. This field is included in the extracted log info

General Conclusions:
1. In case 2 there are 17 decos with the moretrees prefix
2. In case 3 there are 17 decos with the moretrees prefix 
3. In case 4 there are 17 decos with "moretrees:" are loaded
4. Comparing decos in case 2 vs case 3, there are 56 non-moretrees decos removed
5. Comparing decos in case 2 vs case 4, there are 56 non-moretrees decos removed.
6. I have manually validated that all 56 removed decos are from biomes included in ethereal's list of biomes to be removed (so ones it's directly modifying).

Attached are the lists of decos found in each case in case someone wants to double check my analysis 'cause it's fairly late here.  I've also attached a zip with the debug mod I wrote for testing this.

[decos_case_4_moretrees_and_ethereal_deps_reversed.txt](https://github.com/mt-mods/moretrees/files/10192113/decos_case_4_moretrees_and_ethereal_deps_reversed.txt)
[decos_ethereal_alone.txt](https://github.com/mt-mods/moretrees/files/10192115/decos_ethereal_alone.txt)
[decos_case_1_none.txt](https://github.com/mt-mods/moretrees/files/10192116/decos_case_1_none.txt)
[decos_case_2_moretrees.txt](https://github.com/mt-mods/moretrees/files/10192117/decos_case_2_moretrees.txt)
[decos_case_3_moretrees_and_ethereal.txt](https://github.com/mt-mods/moretrees/files/10192118/decos_case_3_moretrees_and_ethereal.txt)
[awk_stats.zip](https://github.com/mt-mods/moretrees/files/10192137/awk_stats.zip)

**Comment by Awkanimus** [comment]
Assuming I haven't missed anything, can we remove that dependency on ethereal from moretrees? Is there something else I should try out?

**Comment by fluxionary** [comment]
+1 on just removing the dependency. what is to be done about ethereal is a separate discussion.

**Comment by wsor4035** [comment]
@Niklp09 since you made the original claim https://github.com/mt-mods/moretrees/pull/11#discussion_r1002973356 here, is this still a valid issue?

**Comment by Awkanimus** [comment]
Looked into ethereal's `biome_init.lua`'s history a bit and commit [ff99917e](https://notabug.org/TenPlus1/ethereal/commit/f99917e067dd73c20c4d5b6916a8e11b320eb29d) is very informative. The behavior @Niklp09 described is corrected in this commit; but anyone who has the previous version of ethereal and hasn't updated it would still fall pray. I can imagine this causing confusion long after the bug is fixed.

In the above commit, ethereal's version is changed to `20220424`; If we want moretrees users to avoid this confusion and think it's worth it, we could do a version check and dump a warning. I'm imagining something like:

```
if ethereal then
    ethereal_ver = tonumber(ethereal.version)
    if (ethereal_ver and ethereal_ver < 20220424) then
        minetest.log("warning", "The version of ethereal detected can result in parts of this mod and others disappearing due to mod load order. Please update ethereal.");
    end
end
```

I'm not sure it's worth it though as the first thing we can ask is what version of ethereal they have if someone reports the issue. Depends on the expected frequency that people will have an old version of ethereal and a new version of moretrees.

**Comment by wsor4035** [comment]
your code would need to be wrapped in a register on mods loaded to always work without a dep on ethereal

**Comment by BuckarooBanzay** [comment]
> block the server process from starting, since its not going to work properly anyways.

this ^ would be the way imo (if we are going the hacky route)

**Comment by wsor4035** [comment]
granted no one has said anything here/discord/irc/matrix in 15h, just going to reopen the pr, and request changes

**Comment by Awkanimus** [comment]
@wsor4035 all done in the pull request. Not sure how to mark this as resolved by that. Please let me know if more is needed.
