### ISSUE TITLE
Circular Dependency  because of moreblocks -> basic_materials -> moreores

### ISSUE THREAD

**Issue by antevens** [mt-mods/moretrees#23]
Currently there are two depedency cycles which both involve moretrees/moreblocks.

Seems like perhaps the easiest way to fix these might be to do it in moretrees but I might be wrong.

The first one is because of flowerpot, the second because of mg as shown.
```
flowerpot -> moretrees -> moreblocks -> basic_materials ->  moreores -> frame -> flowerpot
                                                                     -> mg    -> moretrees
```

**Comment by BuckarooBanzay** [comment]
duplicate of #22 ? 🤔

**Comment by antevens** [comment]
Yup, sorry I missed that when I looked at existing issues, thx.
