### ISSUE TITLE
stupid question: how to get moretrees:raw_coconut?

### ISSUE THREAD

**Issue by superfloh247** [mt-mods/moretrees#25]
title says it all :-)

**Comment by OgelGames** [comment]
Coconut + drinking glass + axe. The result is coconut milk, with raw coconut returned as a replacement:

https://github.com/mt-mods/moretrees/blob/393840ba49880e1ce818fcdb4f3a096ec9100eba/crafts.lua#L109-L123

**Comment by superfloh247** [comment]
I was not aware of replacements =

tyvm
