### ISSUE TITLE
Coconut-milk: axe is not returned when crafting using pipeworks:autocrafter

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/moretrees#3]
Coconut-milk: axe is not returned when crafting using pipeworks:autocrafter
See 89bffdec (comment 317348282)

**Comment by debagos** [comment]
This was an issue with the autocrafter itself. It got fixed in https://github.com/mt-mods/pipeworks/commit/2f97a367f3225fb9db4009952ab2063f4a2471c8
Issue can be closed.

**Comment by OgelGames** [comment]
Oh, right, thanks for pointing this out :)
