### ISSUE TITLE
This mod disables almost every other mod

### ISSUE THREAD

**Issue by Alatarius** [mt-mods/moretrees#34]
When I try to enable this mod, it disables these mods:

3d_armor, animalworld, anvil, area_containers, awards, bakedclay, basic_materials, biofuel, bonemeal, wooden bucket, castle_farming, castle_gates, castle_lighting, castle_masonry, castle_storage, castle_tapestries, connected_chests, cottages, darkage,  deepslate, diggicontrol, digilines, digistuff, digtron, display_modpack, drinks, ethereal, etherium_stuff, everness, factory, flowerpot, prcedural furniture, handle schematics, hopper, leather armor, livingcaves, livingcavesmobs, livingdesert, livingfloatlands, livingjungle, livingnether, lwcomponents, mesebox, experimental villages, mg-villages, micupack, traders, mobs_skeletons, moreblocks, more mesecons, nativevillages, naturalbiomes, nether, new_campfire, obsidianstuff, omnidriver, pipeworks, powerbanks, regrowing fruits, ropes, signs lib, stamina, stripped tree, swamp, technic, technic plus, techpack, ts_furniture, unified_dyes, variety, wilhelminessounds, wine, xdecor, x_enchanting, x_farming

Both mesecons and technic are very popular mods. And mg_villages requires this to be loaded but more_trees disables it.

[edit] I am on minetest 5.8.0 on Minetest Game

**Comment by BuckarooBanzay** [comment]
> but more_trees disables it.

there's no such thing as a mod disabling another mod, please post more infos about your situation, this looks like a missing-dependency problem

**Comment by Alatarius** [comment]
I did find the issue. It was in one of the biome mods. It made almost every mod incompatible and was stating that yours and other mods had errors. I have since removed the mod and all is well in the world again.

**Comment by Alatarius** [comment]
Feel free to remove the thread and review on contentDB.

**Comment by BuckarooBanzay** [comment]
i know this didn't solve your issue but still thanks for reporting bugs :+1:

**Comment by rubenwardy** [comment]
> I did find the issue. It was in one of the biome mods. It made almost every mod incompatible and was stating that yours and other mods had errors. I have since removed the mod and all is well in the world again.

What actually was the issue? Which biome mod?
