### ISSUE TITLE
Incompatible with many popular mods

### ISSUE THREAD

**Issue by Alatarius** [mt-mods/moretrees#49]
I find it sad that I can no longer use this mod as it's incompatible with many, many, mods. I have compiled a list of popular mods and other mods used on my server as well as many other servers. We have all had to disable your mod due to its incompatibility.

This mod is incompatible with:

Popular Mods
---------------------

   - 3D Armor
   - Anvil
   - Awards
   - Digtron
   - Drinks
   - Handle Schematics
   - Hopper
   - Hopper Compatibility
   - Illumination
   - LootChests Modpack
   - Mobs Skeletons
   - More Blocks
   - More Ores
   - Nether
   - Pipeworks
   - Technic
   - Technic Plus
   - Powerbanks
   - Unified Dyes
   - Void Chest
   - Wine
   - X Bows
   - X Enchanting
   - X-Decore-Libre

Others used on my server
---------------------------

- AirUtils
- Wilhelmines Animal World
- Area Containers
- Baked Clay
- Basic Materials and Items
- Biofuel
- Bonemeal
- Bridger
- Wooden Bucket
- bweapons Modpack
- Castle Gates
- Castle Lighting
- Castle Masonry
- Castle Storage
- Castle Tapestries
- Connected Chests
- Darkage
- Deepslate
- Display Modpack
- Ethereal NG
- Etherium Stuff
- New Factory
- Flowerpot
- Procedural Furniture
- Gadgets Modpack
- Hang Glider
- Jumpdrive
- Leather Armor
- Wilhelmines Living Desert
- Wilhelmines Living Floatlands
- Wilhelmines Living Jungle
- Wilhelmines Living Nether
- Log Spikes
- LWComponents
- Magic Materials
- Mesebox
- Experimental Villages
- Micupack
- Mobs Ethereal Bosses
- Wilhelmines More Torches
- Native Villages
- Wilhelmines Natural Biomes
- New Campfire
- NPC You Can Talk To
- Obsidian Stuff Redo
- Wilhelmines People
- Pipeworks Hole Removal
- Regrowing Fruits
- Shipwrecks
- SkinsDB
- stripped tree
- Swamp Biome
- Technic Recipes
- Techpack
- Basic Furniture
- Valleys Mapgen
- Variety
- Wilhelmines Sounds

**Comment by SwissalpS** [comment]
I'm confused because many mods on your list are [also on this meta-repo](https://github.com/pandorabox-io/pandorabox-mods) along with moretrees. I haven't noticed 'unplayable incompatibilities'.

Also how are mods like anvil or illumination even remotely conflicting with this mod by your findings?

**Comment by Alatarius** [comment]
I'm not sure as I'm not a coder and just an end user but when I enable this mod all the other mods listed have a notice that it's incompatible and has issues. It could be possible that one of the map mods breaks this and others. I can try that and get back to you.

**Comment by OgelGames** [comment]
We have this mod on the Pandorabox server where it works perfectly fine with many of the mods you have listed.

Recently `xcompat` was added as a dependency, do you have that mod installed? https://content.minetest.net/packages/mt-mods/xcompat

**Comment by Alatarius** [comment]
Valleys Mapgen was the culprit. If I have that mod active the activating MoreTrees breaks all the other mods listed above. With that mod completely uninstalled then all the mods work fine. I will take this issue to that mod's author. 

Thank you for hearing me out and sorry to have bothered you with this.
